# test this file with
#   goreleaser release --config goreleaser.yml --clean --snapshot
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/surbiks/tls-shunt-proxy/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archives:
  - format: gz
    files:
      - none*
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"